import mongoose from 'mongoose';

/**
 * One document per (shop, calendar day): the owner's end-of-day business
 * summary. Generated by the daily cron (and regenerable on demand) so the
 * dashboard can render history without re-aggregating months of sales.
 */
const dailySummarySchema = new mongoose.Schema({
  shop: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Shop',
    required: true,
    index: true,
  },
  /** Calendar day this summarizes, as YYYY-MM-DD (shop-local business day). */
  date: {
    type: String,
    required: true,
  },
  totals: {
    revenue: { type: Number, default: 0 },
    transactions: { type: Number, default: 0 },
    discounts: { type: Number, default: 0 },
    /** Estimated using current product costPrice (approximation, labeled as such). */
    grossProfit: { type: Number, default: 0 },
    expenses: { type: Number, default: 0 },
  },
  byMethod: {
    cash: { count: Number, total: Number },
    mpesa: { count: Number, total: Number },
    card: { count: Number, total: Number },
  },
  refunds: { count: Number, total: Number },
  voids: { count: Number, total: Number },
  shifts: {
    count: { type: Number, default: 0 },
    /** Sum of drawer discrepancies across closed shifts (negative = short). */
    totalDiscrepancy: { type: Number, default: 0 },
    /** Shifts still open when the summary ran — flagged in the report. */
    unclosed: { type: Number, default: 0 },
  },
  inventory: {
    lowStockCount: { type: Number, default: 0 },
    /** Net quantity moved by manual stock adjustments during the day. */
    adjustments: { type: Number, default: 0 },
    stockValue: { type: Number, default: 0 },
  },
  bestSellers: [{
    productId: { type: mongoose.Schema.Types.ObjectId },
    name: String,
    quantity: Number,
    revenue: Number,
  }],
  slowMovers: [{
    productId: { type: mongoose.Schema.Types.ObjectId },
    name: String,
    quantity: Number,
    stock: Number,
  }],
  staffPerformance: [{
    staffId: { type: mongoose.Schema.Types.ObjectId },
    name: String,
    salesCount: Number,
    revenue: Number,
  }],
  mpesaReconciliation: {
    /** Sales recorded as M-PESA vs confirmed Daraja transactions for the day. */
    salesTotal: { type: Number, default: 0 },
    confirmedTotal: { type: Number, default: 0 },
    delta: { type: Number, default: 0 },
  },
  /** Rule-based, human-readable takeaways rendered in the report UI. */
  insights: [{ type: String }],
  generatedAt: { type: Date, default: Date.now },
  /**
   * Cached Gemini explanation of this day's BusinessSnapshot. `fingerprint`
   * is a cheap digest of today's revenue/transactions/expenses/profit at the
   * time this was generated — NOT this doc's own `generatedAt`, which bumps
   * on every dashboard/summary read regardless of whether anything actually
   * changed. Only regenerate via Gemini when the fingerprint no longer
   * matches today's current totals (i.e. a new sale/expense/refund landed).
   * No separate cache collection needed.
   */
  aiInsight: {
    summary: { type: String },
    priority: { type: String, enum: ['low', 'medium', 'high'] },
    actions: [{ type: String }],
    health: { type: Number },
    fingerprint: { type: String },
    generatedAt: { type: Date },
  },
}, {
  timestamps: true,
});

dailySummarySchema.index({ shop: 1, date: -1 }, { unique: true });

export default mongoose.model('DailySummary', dailySummarySchema);
